N: 12000 #total steps
dt: 0.001 #ms
distance: 1500 #micrometers
dx: 0.1 #micrometer

R: 7 #resistance from electrode to neuron
ALPHA: 4 #offset parameter
BETA: 1 
TAU: 10 #ms
Rm: 1 #membrane resistance
THRESHOLD: 20 #mV
intensity: 500 #microamps
P: 2 #Power law

rates:
  exc: 1 #Hz
  inh: 2 #Hz

sigmas:
  ee: 127
  ie: 96.6
  ei: 99.84
  ii: 126.77

#Activation init
act_weights:
  ee: 1200
  ie: 200
  ei: 400
  ii: 150

gamma:
  exc: 10000
  inh: 0

#No boost init
no_boost_weights:
  ee: 150
  ie: 150
  ei: 150
  ii: 150

no_boost:
  exc: 1
  inh: 1

# Axon Parameters
MU_E: 0.45
MU_I: 0.54
STDEV_E: 0.1
STDEV_I: 0.1
RHEOBASE: 5
PULSE: 12
STEP: 1e-6